### ISSUE TITLE
TypeError: nextProps.transitionInterpolator.arePropsEqual is not a function

### ISSUE THREAD

**Issue by liamrohan** [leighhalliday/house-course#3]
![Screenshot 2021-02-13 at 12 14 26](https://user-images.githubusercontent.com/29813120/107849715-17e17a00-6df5-11eb-8c75-51265646ce62.png)
nextProps.transitionInterpolator.arePropsEqual is not a function

Hi Leigh, receiving this error and can't seem to find a fix, I've tried playing around with different react-map-gl versions on my local, still to no avail. 

To rule out any monkey code of mine I've just initialised a fresh repo clone and receiving the same issue. 

New to TS, - don't suppose you are seeing the same error on your side? 
![Screenshot 2021-02-13 at 11 37 59](https://user-images.githubusercontent.com/29813120/107849052-77895680-6df0-11eb-80e9-a03ad447c339.png)

**Comment by exponent42** [comment]
From one of your previous videos: https://github.com/leighhalliday/mapbox-clustering/blob/3cdee3ee9d9ad4b90026fb1c91ad78f4d456d62f/src/App.js#L3

`FlyToInterpolator` required ?

**Comment by liamrohan** [comment]
EDIT: found that `bounds` in some instances was returning `undefined` therefore added aync / await to `const bounds` and this seems to have solved it. 

Realised this really simple fix moments ago, I assumed it was a problem with the `react-map-gl` config.
